### ISSUE TITLE
Remove klog dependency

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kube-openapi#117]
The error surfacing in this package should be self evident. 

A self-contained system like Kubernetes which imports kube-openapi may use logging module (glog/klog) to do V-style logging. However this package don't have a good reason to use glog/klog, which interferes/makes assumption about logging mechanism used by downstream systems.

ref: https://github.com/kubernetes/kube-openapi/pull/115

/good-first-issue
/help

**Comment by palash25** [comment]
Hi @roycaihw new contributor here :wave: would like to take a crack at this issue. Just need clarification on one thing, if we don't want logging what would you want it to be replaced by? `print` statements?

**Comment by devdattakulkarni** [comment]
@roycaihw Can you elaborate on what would it take to resolve this issue?
