### ISSUE TITLE
Seeking advice for generating openapi spec for CRD

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kube-openapi#13]
@mbohlool , is there an example on how to use this generator to generate/serve open api spec for CRDs from GO types?

From https://github.com/kubernetes-client/java/issues/96, I am looking for ways to generate non-Go client for CRDs. 

Any help is much appreciated!

**Comment by mbohlool** [comment]
There are two parts in OpenAPI generation and handling:

1- Generating a model from a go type. This should be possible with this library. Look at my answer to [this stackoverflow thread](https://stackoverflow.com/questions/46592085/go-structs-to-openapi-to-jsonschema-generation-automatically/46615249#46615249).

2- Creating the OpenAPI spec from the model generated in 1. You need to also add routing and call the builder package. For CRD those operation are standard k8s CRUD operations. I would like to see we add support for CRD OpenAPI spec to kubernetes then you can get the spec from kubernetes. But you can also provide the CRUD operation by hand or copy one of the other API object spec and plug in your model in it.

3- When you got your OpenAPI spec then you should be able to generate a client using https://github.com/kubernetes-client/gen. After generation you may need to copy the useful utilities from the language repo. For example for python [this is the repo](https://github.com/kubernetes-incubator/client-python).

**Comment by tamalsaha** [comment]
Thanks a lot @mbohlool ! I will give it a try and see how it goes.

**Comment by tamalsaha** [comment]
@mbohlool , I was able to generate openapi spec from appscode/voyager project.

generated spec: https://github.com/appscode/voyager/blob/master/apis/voyager/v1beta1/openapi_generated.go

Generator command: https://github.com/appscode/voyager/blob/0370feff31c1012c3e94a52bb4218136ca6e4a42/hack/codegen.sh#L51

I am not sure what is the next step? How do I server this spec so that swagger generators cab access them?

**Comment by mbohlool** [comment]
This generates only models. You need to provide a route list to `pkg/builder` of `kube-openapi` repo to get an `spec.Swagger` that is a final spec. You can serve that directly yourself or you can use `kube-openapi/pkg/handler` to do that (handler have a connivance method that accept parameters for both builder and handler, then build and handle the spec. main kubernetes repo call that method, so you can check that for an example of how to serve OpenAPI spec).

**Comment by erictune** [comment]
xref https://github.com/kubernetes/code-generator/issues/28

**Comment by jessesuen** [comment]
In case others can benefit from this, I wasn't able to get this to work using only kube-openapi. Instead I constructed the go-openapi `spec.Swagger ` directly and fed it the models which were generated by kube-openapi. The solution can be seen here:
https://github.com/argoproj/argo/blob/master/hack/gen-openapi-spec/main.go

which generates this:
https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json

**Comment by tamalsaha** [comment]
@jessesuen your swagger.json is missing the api call information. To generate client that information will be needed.

**Comment by tamalsaha** [comment]
I have figured out how to get this to work. Here is my working demo: https://github.com/tamalsaha/kube-openapi-generator
