### ISSUE TITLE
Error `API rule violation: list_type_missing` is faced when the type is `[]string`

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes/kube-openapi#175]
We are using `k8s.io/kube-openapi v0.0.0-20190603182131-db7b694dc208` and facing `API rule violation: list_type_missing` when the impl is as follows. 

```go
// Status of Nodes
Nodes []string `json:"nodes"`
```

So, we would like to know if is a bug or the expected behaviour? If it is a bug, could you help us by letting us know if it is solved already? 

We could solve the validation issue by doing as follows. 

```go
// MemcachedStatus defines the observed state of Memcached
// +k8s:openapi-gen=true
type MemcachedStatus struct {
	// Nodes are the names of the memcached pods
	// +kubebuilder:validation:UniqueItems=true
	Nodes PodList `json:"nodes"`
}

// PodList is a list of names of pods
type PodList struct {
	Names []string
}

func NewPodList(value []string) PodList {
	p := PodList{Names: value}
	return p
}
```
Extra : 

Following the others lbs/versions used with as well. 

```go
         k8s.io/api => k8s.io/api v0.0.0-20190409021203-6e4e0e4f393b
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.0.0-20190409022649-727a075fdec8
	k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20190404173353-6a84e37a896d
	k8s.io/client-go => k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a+incompatible
	k8s.io/cloud-provider => k8s.io/cloud-provider v0.0.0-20190409023720-1bc0c81fa51d
```

**Comment by sttts** [comment]
It is expected because kube-opanapi now expects list-type tags on slices as preparation of server-side-apply. @apelisse knows more.

We have hundreds of exception in kube itself: https://github.com/kubernetes/kubernetes/blob/36981002246682ed7dc4de54ccc2a96c1a0cbbdb/api/api-rules/violation_exceptions.list

**Comment by apelisse** [comment]
I'm currently looking at the documentation for all things related to that, so thanks for the report.
Ideally, we'll document this properly and then enforce this a little stronger.

**Comment by camilamacedo86** [comment]
Really thanks. @sttts and @apelisse for the confirmation.
Please, feel free to close this one if you wish or keep open to tracking the need to doc that.

**Comment by alculquicondor** [comment]
How do you set the type?

**Comment by camilamacedo86** [comment]
Hi @alculquicondor,
 
See [here](https://github.com/operator-framework/getting-started#define-the-memcached-spec-and-status) in the Getting Started an example. Also, now you can find its info in the migration doc as well.

**Comment by apelisse** [comment]
We have done a lot of efforts to improve the documentation and we're keeping track of it somewhere else, I'm closing this now. FYI @mariantalla 

/close

**Comment by vsoch** [comment]
If anyone else wanders to this issue trying to solve this bug (using the generator for the first time) I found the answer here: https://github.com/kubernetes/kube-openapi/blob/66828de6f33bb80ef329278e7cbaed94bc9d1abe/pkg/idl/doc.go#L21
When I added one of those annotations on top of the offending structs, the error went away. In case that link goes away

> ListType annotates a list to further describe its topology. It may have 3 possible values: "atomic", "map", or "set". Note that there is no default, and the generation step will fail if a list is found that is missing the tag. This tag MUST only be used on lists, or the generation step will fail.


```go
// Atomic
+listType=atomic

// Atomic lists will be entirely replaced when updated. This tag may be
// used on any type of list (struct, scalar, ...).

// Map
+listType=map

// These lists are like maps in that their elements have a non-index key
// used to identify them. Order is preserved upon merge. Using the map
// tag on a list with non-struct elements will result in an error during
// the generation step.

// Set
+listType=set

// Sets are lists that must not have multiple times the same value. Each
// value must be a scalar (or another atomic type).
```
