### ISSUE TITLE
Add support for +mapType, +structType

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kube-openapi#177]
The two annotations used to describe the topology of maps and structs, `+mapType` and `+structType`, should result in generating the equivalent openapi extensions (`x-kubernetes-map-type` and `x-kubernetes-struct-type` respectively). This is [documented](https://github.com/kubernetes/kube-openapi/blob/0270cf2f1c1d995d34b36019a6f65d58e6e33ad4/pkg/idl/doc.go) but not implemented at the moment.

/assign
(have a tiny PR in progress at the moment)

**Comment by sttts** [comment]
:+1:

**Comment by sttts** [comment]
Can you do the same addition to controller-tools? (compare https://github.com/kubernetes-sigs/controller-tools/pull/345 for an example). I would like to make sure we use the same markers for both kube-openapi and kubebuilder's controller-tools.

cc @DirectXMan12

**Comment by mariantalla** [comment]
Yep, coming up next (sorry, should have created an issue 🤦‍♀ will go ahead and do that now). Thanks for the pointer too 🙏
