### ISSUE TITLE
Allow properties to be skipped from the generation

### ISSUE THREAD

**Issue by jpkrohling** [kubernetes/kube-openapi#180]
In the Jaeger Operator, we have structs similar to this:

```go
// +k8s:openapi-gen=true
type JaegerSpec struct {
	// +optional
	JaegerCommonSpec `json:",inline,omitempty"`
}

type JaegerQuerySpec struct {
	// +optional
	JaegerCommonSpec `json:",inline,omitempty"`
}

type JaegerCollectorSpec struct {
	// +optional
	JaegerCommonSpec `json:",inline,omitempty"`
}

// and a bunch of other types embedding the common spec

// +k8s:openapi-gen=true
type JaegerCommonSpec struct {
	// +optional
	Volumes []v1.Volume `json:"volumes,omitempty"`

	// +optional
	Affinity *v1.Affinity `json:"affinity,omitempty"`

	// a bunch of other fields here...
}
```

Generating the CRD with the OpenAPI Schema generates a CRD with 1.3M:

```console
$ ls -lah deploy/crds/jaegertracing.io_jaegers_crd.yaml
-rw-r--r--. 1 jpkroehling wheel 1,3M 29. Nov 16:56 deploy/crds/jaegertracing.io_jaegers_crd.yaml
```

Kubernetes, in turn, refuses this CRD:

```console
The CustomResourceDefinition "jaegers.jaegertracing.io" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

Unfortunately, it looks like overriding the tag `k8s:openapi-gen` to `false` in the `JaegerCommonSpec` type has no effect. Neither has overriding the tag at the property level, so, my request here is to allow properties to be skipped from the schema generation.

**Comment by yue9944882** [comment]
per-field `// +k8s:openapi-gen=false` tag should work i remember, did you try that?

**Comment by jpkrohling** [comment]
Indeed, I just tried it on a simplified new project and `+k8s:openapi-gen=false` is effective. Closing.
