### ISSUE TITLE
Items fields in List types do not need annotations

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kube-openapi#185]
https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/rules/idl_tag.go#L25

This code needs to make an exception for List types (served as a result of a LIST verb and never a target for a mutating operation).

If:
* There's a `Metadata v1meta.ListMeta` sibling field AND
* The field is named "Items" and is a list of something

Then we should actually require that people NOT include a listType= annotation. (and ideally, suppress emitting the tag in the resulting openapi spec)

Why? Otherwise people have to add an exception for this, and I don't want people doing that for nothingburgers, it's bad karma.

**Comment by mariantalla** [comment]
Closing this, let's reopen if needed.

/close

**Comment by lavalamp** [comment]
Do we need to bump the version in k/k to start giving people the new error
messages?

**Comment by apelisse** [comment]
Yeah, I suspect that's also going to force us to remove a lot of the "exceptions", which is always good.

**Comment by apelisse** [comment]
@mariantalla Do you want to take care of it? (not today ;-)
