### ISSUE TITLE
Create a kube-openapi documentation

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kube-openapi#19]
Write a full documentation on how to use Kube-OpenAPI.

**Comment by anubhakushwaha** [comment]
@mbohlool It will be really awesome to have this please.

**Comment by anubhakushwaha** [comment]
@nikhita Any idea if this was updated/documented?

**Comment by nikhita** [comment]
> @nikhita Any idea if this was updated/documented?

Afaik no, it wasn't updated.

/remove-lifecycle stale

**Comment by Jeffwan** [comment]
Documentation would be really helpful.. It's not beginner friendly..
