### ISSUE TITLE
Downgrade to gnostic v0.1.0?

### ISSUE THREAD

**Issue by Hyzhou** [kubernetes/kube-openapi#207]
newest client-go@v0.18.8 used gnostic@v0.1.0 only.
package "github.com/googleapis/gnostic/openapiv2" and "github.com/googleapis/gnostic/OpenAPIv2" was conflict.

It caused a big dependency problem.

**Comment by c10l** [comment]
Is there a workaround for this issue? I'm trying to build a CRD using latest kubebuilder but I'm stuck trying to create an API because of this...
