### ISSUE TITLE
hardcoded `git checkout` path at $GOPATH/src/k8s.io, is required, to pass `go test`, using github-actions

### ISSUE THREAD

**Issue by longwuyuan** [kubernetes/kube-openapi#225]
Hi,

In github-actions ci, _"go test"_ fails, unless a _"mkdir $GOPATH/src/k8s.io"_ is done  _"$GOPATH/src"_ and _"git clone"_ is executed under _$GOPATH/src/k8s.io"_  .

But _"go build"_ works without the above specific path. So I am assuming that some piece of code under $PROJECT_HOME/test needs looking into.

Details here https://github.com/kubernetes/kube-openapi/pull/226

**Comment by longwuyuan** [comment]
@nikhita @dims

**Comment by longwuyuan** [comment]
https://github.com/kubernetes/kube-openapi/pull/226#issuecomment-772117989

**Comment by longwuyuan** [comment]
A youtube video on Go tutorial says the first GOPATH gets used for dependencies but a second GOPATH works for custom directory tree of src. Need to test and read relevance to Go version ^1.14 .

**Comment by apelisse** [comment]
There's a path variable in the checkout module that lets you chose where to check out, have you tried that?

**Comment by apelisse** [comment]
@liggitt Clearly that's the problem :-)

**Comment by longwuyuan** [comment]
I thought i tried the path option and i thought even the path  option forced checkout path as a subdir under "/home/runner/work" but the tests only look under $GOPATH /home/runner/go even though GO111MODULES=on was used.

Checking again now

**Comment by apelisse** [comment]
You should be able to use GOPATH to set-up your path accordingly?

**Comment by longwuyuan** [comment]
I just forked again and hoping to use the checkout action and GOPATH as you advised. WIll update asap.

**Comment by longwuyuan** [comment]
> You should be able to use GOPATH to set-up your path accordingly?

- Using github-action module checkout ;
  - build passes, test fails with reason 

     ```
      STEP: building openapi-gen
    Failure [0.001 seconds]
    [BeforeSuite] BeforeSuite 
    /home/runner/work/kube-openapi/kube-openapi/test/integration/integration_suite_test.go:68
    
      Expected error:
          <*errors.errorString | 0xc000091620>: {
              s: "$GOPATH not provided when building ../../cmd/openapi-gen/openapi-gen.go",
          }
          $GOPATH not provided when building ../../cmd/openapi-gen/openapi-gen.go
      not to have occurred
    
      /home/runner/work/kube-openapi/kube-openapi/test/integration/integration_suite_test.go:81
    ------------------------------
    
    Ran 3 of 0 Specs in 0.001 seconds
    FAIL! -- 0 Passed | 3 Failed | 0 Pending | 0 Skipped --- FAIL: TestGenerators (0.00s)
    FAIL
    FAIL	k8s.io/kube-openapi/test/integration	0.007s
    ?   	k8s.io/kube-openapi/test/integration/builder	[no test files]
    ?   	k8s.io/kube-openapi/test/integration/pkg/generated	[no test files]
    FAIL
    Error: Process completed with exit code 1.
    ```
- Using github-actions module checkout AND providing explicit GOPATH=/home/runner/go to "go test"
  - build passes, test fail with reason 

   ```
  STEP: building openapi-gen
  STEP: processing go idl with openapi-gen
  F0305 02:08:35.082442    6105 config.go:57] Failed loading boilerplate: open /home/runner/go/src/k8s.io/kube-openapi/boilerplate/boilerplate.go.txt: no such file or directory
  goroutine 1 [running]:
  k8s.io/klog/v2.stacks(0xc0000b0001, 0xc001b670e0, 0xaf, 0x102)
	  /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:972 +0xb9
  k8s.io/klog/v2.(*loggingT).output(0xdbc2c0, 0xc000000003, 0x0, 0x0, 0xc0000de4d0, 0xd5a510, 0x9, 0x39, 0x0)
	  /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:921 +0x191
  k8s.io/klog/v2.(*loggingT).printf(0xdbc2c0, 0x3, 0x0, 0x0, 0xa244e8, 0x1e, 0xc0073dfd28, 0x1, 0x1)
	  /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:733 +0x17a
  k8s.io/klog/v2.Fatalf(...)
	  /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1427
  k8s.io/kube-openapi/pkg/generators.Packages(0xc0000de460, 0xc0001400a0, 0xa0da10, 0xd, 0xc0000de460)
	  /home/runner/work/kube-openapi/kube-openapi/pkg/generators/config.go:57 +0x118
  k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0001400a0, 0xc0073dfe38, 0xa0da10, 0xd, 0xa3d1e8, 0x0, 0x0)
	  /home/runner/go/pkg/mod/k8s.io/gengo@v0.0.0-20200413195148-3a45101e95ac/args/args.go:206 +0x1a9
  main.main()
	  /home/runner/work/kube-openapi/kube-openapi/cmd/openapi-gen/openapi-gen.go:50 +0x352
  
  goroutine 19 [chan receive]:
  k8s.io/klog/v2.(*loggingT).flushDaemon(0xdbc2c0)
	  /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1107 +0x8b
  created by k8s.io/klog/v2.init.0
	  /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:416 +0xd8
  Failure [4.121 seconds]
  [BeforeSuite] BeforeSuite 
  /home/runner/work/kube-openapi/kube-openapi/test/integration/integration_suite_test.go:68
  
    No future change is possible.  Bailing out early after 2.982s.
    Expected
        <int>: 255
    to match exit code:
        <int>: 0
  
    /home/runner/work/kube-openapi/kube-openapi/test/integration/integration_suite_test.go:98
  ------------------------------
  
  Ran 3 of 0 Specs in 4.124 seconds
  FAIL! -- 0 Passed | 3 Failed | 0 Pending | 0 Skipped --- FAIL: TestGenerators (4.12s)
  FAIL
  FAIL	k8s.io/kube-openapi/test/integration	4.132s
  ?   	k8s.io/kube-openapi/test/integration/builder	[no test files]
  ?   	k8s.io/kube-openapi/test/integration/pkg/generated	[no test files]
  FAIL
  Error: Process completed with exit code 1.
    ```
- The details are here https://github.com/longwuyuan/kube-openapi/runs/2036384104?check_suite_focus=true 
- I will now try other options
- There is a glaring change in checkout@v2 here https://github.com/actions/checkout that says this ;

  ```
  The input path is always relative to $GITHUB_WORKSPACE
  ```
   This change is relevant to our case because we need k8s.io directory under $GOPATH to pass the test and this 
    change forces checkout to be placed under a subdir of /home/runner/work while $GOPATH is outside of this scope 
    at  /home/runner/go. This occurs even with the path variable of checkout module

    I will now be trying all possible options I can think of, including but not limited to symlinking, checkout@v1  etc

**Comment by apelisse** [comment]
OK All these errors look like what I would have expected. Have you tried something like this (omitting things that are irrelevant to my point):
```yaml
- uses: actions/checkout@v2
  with:
    path: src/k8s.io/ # I'm not sure whether you need to include kube-openapi here, let's assume you don't
- name: Set up Go
   uses: actions/setup-go@v2
   with:
     go-version: '1.16' # Let's hardcode a version here so there's no surprise.
- name: Test
   run: cd src/k8s.io/kube-openapi/ && GOPATH=${GITHUB_WORKSPACE} go test ./cmd/... ./pkg/... ./test/...
```
Does that make sense?

**Comment by longwuyuan** [comment]
Thanks tons for these tips. I recall having what you suggested during my first attempt at this PR. But that path under /home/runner/go/src/k8s.io does not work because checkout@v2 only wants to use /home/runner/work even with path.

But we don't have a live working config and a run like that. So I will now configure that in my fork so we can have a clear config with path variable and a related pipeline run to look at. Will update asap. It will be here to look at https://github.com/longwuyuan/kube-openapi/actions

**Comment by apelisse** [comment]
I'm not sure I follow you here. As long as the directories are structured properly (`$GOPATH/src/k8s.io/kube-openapi`), we're good, even if GOPATH is only set while the test runs.

**Comment by longwuyuan** [comment]
Sorry for not being clear and explicit.
The _path_ env var of the checkout@v2 module is relative to $GITHUB_WORKSPACE and I am assuming that will not help to checkout the code to /home/me/go/src/k8s.io/kube-openapi . However I am configuring it to use the path variable as you suggested so we can have a run and hopefully know if I am assuming wrong

**Comment by longwuyuan** [comment]
@apelisse after making the changes you sugested, build works (with corresponding cd command) but test fails with the reason ;

```
  STEP: building openapi-gen
  STEP: processing go idl with openapi-gen
  F0305 07:27:10.720969    6587 config.go:57] Failed loading boilerplate: open /home/runner/work/kube-openapi/kube-openapi/src/k8s.io/kube-openapi/boilerplate/boilerplate.go.txt: no such file or directory
  goroutine 1 [running]:
  k8s.io/klog/v2.stacks(0xc0000b8001, 0xc001be1200, 0xcb, 0x11e)
	  /home/runner/work/kube-openapi/kube-openapi/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:972 +0xb9
  k8s.io/klog/v2.(*loggingT).output(0xd49c40, 0xc000000003, 0x0, 0x0, 0xc0000e6540, 0xb23a45, 0x9, 0x39, 0x0)
	  /home/runner/work/kube-openapi/kube-openapi/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:921 +0x191
  k8s.io/klog/v2.(*loggingT).printf(0xd49c40, 0x3, 0x0, 0x0, 0x9e5553, 0x1e, 0xc006529d28, 0x1, 0x1)
	  /home/runner/work/kube-openapi/kube-openapi/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:733 +0x17a
  k8s.io/klog/v2.Fatalf(...)
	  /home/runner/work/kube-openapi/kube-openapi/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1427
  k8s.io/kube-openapi/pkg/generators.Packages(0xc0000e64d0, 0xc00015e000, 0x9cee21, 0xd, 0xc0000e64d0)
	  /home/runner/work/kube-openapi/kube-openapi/src/k8s.io/pkg/generators/config.go:57 +0x11e
  k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc00015e000, 0xc006529e38, 0x9cee21, 0xd, 0x9fdf20, 0x0, 0x0)
	  /home/runner/work/kube-openapi/kube-openapi/pkg/mod/k8s.io/gengo@v0.0.0-20200413195148-3a45101e95ac/args/args.go:206 +0x1b7
  main.main()
	  /home/runner/work/kube-openapi/kube-openapi/src/k8s.io/cmd/openapi-gen/openapi-gen.go:50 +0x352
  
  goroutine 19 [chan receive]:
  k8s.io/klog/v2.(*loggingT).flushDaemon(0xd49c40)
	  /home/runner/work/kube-openapi/kube-openapi/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1107 +0x8b
  created by k8s.io/klog/v2.init.0
	  /home/runner/work/kube-openapi/kube-openapi/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:416 +0xd8
  Failure [4.017 seconds]
  [BeforeSuite] BeforeSuite 
  /home/runner/work/kube-openapi/kube-openapi/src/k8s.io/test/integration/integration_suite_test.go:68
  
    No future change is possible.  Bailing out early after 3.005s.
    Expected
        <int>: 255
    to match exit code:
        <int>: 0
  
    /home/runner/work/kube-openapi/kube-openapi/src/k8s.io/test/integration/integration_suite_test.go:98
  ------------------------------
  
  Ran 3 of 0 Specs in 4.019 seconds
  FAIL! -- 0 Passed | 3 Failed | 0 Pending | 0 Skipped --- FAIL: TestGenerators (4.02s)
  FAIL
  FAIL	k8s.io/kube-openapi/test/integration	4.032s
  ?   	k8s.io/kube-openapi/test/integration/builder	[no test files]
  ?   	k8s.io/kube-openapi/test/integration/pkg/generated	[no test files]
  FAIL
  Error: Process completed with exit code 1.
```

**Comment by longwuyuan** [comment]
@apelisse I have confirmed that if I symlink the root of the checked-out code to a name "kube-openapi", the test pass.

This run with a symlink is visible at https://github.com/longwuyuan/kube-openapi/runs/2038034390?check_suite_focus=true

**Comment by longwuyuan** [comment]
@apelisse Submitted a PR ;
- Used githubaction checkout@v2 out to path _${GITHUB_WORKSPACE}/src/k8s.io/kube-openapi/_
- Doing a  _cd ${GITHUB_WORKSPACE}/src/k8s.io/kube-openapi_ for build and test

Test passed

PS - Sincere apologies for so much time on a (now) seemingly trivial and obvious aspect. Beginner to go.

**Comment by longwuyuan** [comment]
@dims cc

**Comment by longwuyuan** [comment]
resolved for now with https://github.com/kubernetes/kube-openapi/pull/232
