### ISSUE TITLE
Incomplete OpenAPI operation responses

### ISSUE THREAD

**Issue by galdor** [kubernetes/kube-openapi#227]
In the current state, the generated OpenAPI document does not include all response types in operations, and those which are defined do not always include a schema.

For example:
```json
"responses": {
  "200": {
    "description": "OK",
    "schema": {
      "$ref": "#/definitions/io.k8s.api.core.v1.PodList"
    }
  },
  "401": {
    "description": "Unauthorized"
  }
},
```

This is a problem because code generators cannot emit validation code or even just type signatures for functions sending requests.

Is there a reason this information is missing ?

**Comment by gearnode** [comment]
@fejta-bot /remove-lifecycle stale

**Comment by galdor** [comment]
Does anyone care ? If not, is the project active ? If Kube does not officially support this OpenAPI specification, it would be nice to know.

/remove-lifecycle stale

**Comment by galdor** [comment]
Does someone even care ? Is the OpenAPI schema even maintained ? If not, could you please archive this repository so that people like me do not waste time reporting issues which will go straight to /dev/null ?

/remove-lifecycle rotten
