### ISSUE TITLE
"module-aware" mode is not working during "go test", in github-actions CI pipeline

### ISSUE THREAD

**Issue by longwuyuan** [kubernetes/kube-openapi#233]
@apelisse @dims Please advise and will do accordingly.

- Problem
While running github-actions CI, using go v.1.16, "go test" fails if GOPATH is not passed explicit to "go test"

- Description
  - module-aware mode is "on" by default in go version 1.16. So GOPATH should not be be required, as 
    there is a "go.mod" file in the root of the repo
  - But "go test" fails in github-actions CI as well as on laptop if GOPATH is not passed to "go-test"
  - This happens even in go version 1.15
  - We are currently checking out code to ${GITHUB/WORKSPACE}/src/k.io/kube-openapi/ .  Then we cd into that directory for go build and go test.
  - "go build" works from any directory path. But "go test" works only and only from $GOPATH/src/k8s.io/kbeopenapi/

- Pull Requests  #226 ,  #232  and Issue #225 are related to this
- Will close this issue if this not need to be tracked

**Comment by apelisse** [comment]
I'd really like that issue to be solved. We're using GOPATH explicitly in the test, we clearly need to remove that dependency.

**Comment by longwuyuan** [comment]
Thanks tons for the informative comment @apelisse. Humble request, could you kindly confirm its not trivial enough for a beginner. And hence we just keep this issue for tracking at least. ( just did a grep -ir GOPATH test) and got nothing :-)

**Comment by apelisse** [comment]
I don't really know how it would be solved to be honest. It might be easy, but I haven't spent the time. It's probably doable for a beginner, but it's going to require getting your hands dirty. That's probably the best way to learn ;-)

**Comment by longwuyuan** [comment]
scared, i just saw this ;

```
$ grep "k8s.io/kube-openapi" -ir test | wc -l
77
```

Not likely simply enough to just to a find/replace ... !  Have to evaluate impact of each line changed I guess !  or even study the package name thingall over the place !
