### ISSUE TITLE
Field path reported in validation errors within slice is incorrect

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kube-openapi#262]
I noticed when validating a custom resource using the apiextensions [NewSchemaValidator](https://github.com/kubernetes/apiextensions-apiserver/blob/4c1a29cbb037397b8bd796378443a06075a64a83/pkg/apiserver/validation/validation.go#L33) (which is using the [SchemaValidator](https://github.com/kubernetes/kube-openapi/blob/ee342a809c29ce286ab48cea8442ef9cd0ab8c1c/pkg/validation/validate/schema.go#L34) in this repo) that when a validation error occurs within a slice, the index of the slice is omitted from the fieldpath returned in the error.

YAML snippet:
```
spec:
  dependsOn:
    - provider: registry.upbound.io/crossplane/provider-aws
      version: 1
```
Output:
```
spec.dependsOn.version in body must be of type string: "integer"
```

I looked into why this is happening by traversing through the recursive validation that is performed against the schema. When we get to a the `sliceValidator` for `spec.dependsOn`, it's `Applies()` call returns `true`, causing it to be run.

![Screenshot from 2021-11-05 11-51-07](https://user-images.githubusercontent.com/31777345/140539516-f0e47b6f-e53a-4010-a183-1c830604bbb2.png)

Looking good so far. When the validation actually runs, we get the length for the slice and construct a new `SchemaValidator` that we will reuse to validate each item (just one item in this case).

![Screenshot from 2021-11-05 11-54-40](https://user-images.githubusercontent.com/31777345/140540032-e5a21be9-1463-426e-a054-5b2fcb1ab077.png)

When we first construct this nested `SchemaValidator` we set the path to match the parent validator (`spec.dependsOn`). This is not accurate though and needs to be updated on each iteration, so we call `SetPath()`. After setting the path, we can see that the validator has the proper index appended (`spec.dependsOn.0`).

![Screenshot from 2021-11-05 11-58-53](https://user-images.githubusercontent.com/31777345/140540748-d3efeb48-4079-4371-a453-624b47d82480.png)

Still looking good (though the format is a bit strange, more on this below). Unfortunately, the [initial call](https://github.com/kubernetes/kube-openapi/blob/ec1f4c89925aaed16de489e6daa816bed3bd2811/pkg/validation/validate/schema.go#L81) to `NewSchemaValidator()` is when each of its child validators are instantiated (e.g. `formatValidator`, `objectValidator`, etc.), and the subsequent call to `SetPath()` updates the `SchemaValidator` path, but none of the child validator paths (so now the `SchemaValidator` has path `spec.dependsOn.0`, but all child validators have path `spec.dependsOn`). This can be observed when we iterate through each of the child validators and compare their path with the `SchemaValidator`:

![Screenshot from 2021-11-05 12-04-24](https://user-images.githubusercontent.com/31777345/140541581-757db139-fa56-41c7-9f14-e3e15f18be81.png)

Unfortunately this means that if an error occurs anywhere in any descendant validator, the index of the slice is omitted from the field path (as seen at beginning of the ticket). I have also verified that this is happening in the API server validation (that consumes this repo):

> Note: this example is using a different resource.
```
$ kubectl apply -f definition.yaml --validate=false
The CompositeResourceDefinition "compositepostgresqlinstances.database.example.org" is invalid: spec.versions.referenceable: Invalid value: "string": spec.versions.referenceable in body must be of type boolean: "string"
```

I imagine most users are not catching this because the client-side validation provides a more accurate error:
```
$ kubectl apply -f definition.yaml 
error: error validating "definition.yaml": error validating data: ValidationError(CompositeResourceDefinition.spec.versions[0].referenceable): invalid type for io.crossplane.apiextensions.v1.CompositeResourceDefinition.spec.versions.referenceable: got "string", expected "boolean"; if you choose to ignore these errors, turn validation off with --validate=false
```

## Proposal

I would like to propose two changes, and I am happy to implement them:
1. Set path for child validators in `SchemaValidator` `SetPath()`

The simplest fix is to set the path for all child validators when the path is set on `SchemaValidator`. Though I believe there could be some more elegant handling of paths while performing this traversal, this does address the issue and is a lightweight change to fix this in the immediate term.
```
// SetPath sets the path for this schema validator
func (s *SchemaValidator) SetPath(path string) {
	s.Path = path
	for _, v := range s.validators {
		v.SetPath(path)
	}
}
```
I have verified that this works correctly:
```
spec.dependsOn.0.version in body must be of type string: "integer"
```

2. Use [JSONPath](https://tools.ietf.org/id/draft-goessner-dispatch-jsonpath-00.html) syntax for indices

To be more aligned with client-side validation, and for a more generally accepted format, it would be great to represent that index of a slice as `dependsOn[0]` instead of `dependsOn.0`.

If both of these fixes sound reasonable to folks, I'll go ahead and open PRs to address.

/assign
/bug

**Comment by hasheddan** [comment]
Pinging a few relevant folks to get feedback on proposal :) @apelisse @sttts I would love to get this opened and merged quickly if y'all are on board 👍🏻 Thanks for the work y'all do here!

**Comment by apelisse** [comment]
I'd love to see and comment on a PR for that, I agree that the JSONPath is more consistent with the general consensus and is consistent with what @kevindelgado is doing for return strict decoding errors.

While reading your description and the code, it's not clear to me why we're not creating a new validator for each individual child rather than do what you suggest in 1.? Happy to have this discussion on the pull-request though.

**Comment by hasheddan** [comment]
@apelisse I think there may be some confusion around my terminology for parent and child validators (given the recursive nature of the validation we are performing here). What I am actually referring to is the `SchemaValidator` (parent) and the specific type validators it contains (children). I have opened a PR with fixes here: https://github.com/kubernetes/kube-openapi/pull/273

Looking forward to your review!
