### ISSUE TITLE
changes around VisitArbitary rename broke building an initializer

### ISSUE THREAD

**Issue by xinyanmsft** [kubernetes/kube-openapi#27]
we have an Go app that run as an Kubernetes initializer. It imports the following:

    "k8s.io/client-go/tools/clientcmd"

    "github.com/ghodss/yaml"

    "k8s.io/api/apps/v1beta1"
    corev1 "k8s.io/api/core/v1"
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
    "k8s.io/apimachinery/pkg/fields"
    "k8s.io/apimachinery/pkg/runtime"
    "k8s.io/apimachinery/pkg/types"
    "k8s.io/apimachinery/pkg/util/strategicpatch"
    "k8s.io/apimachinery/pkg/watch"
    "k8s.io/client-go/kubernetes"
    "k8s.io/client-go/rest"
    "k8s.io/client-go/tools/cache"

And then invokes 2 two merge this way: 
patchBytes, err := strategicpatch.CreateTwoWayMergePatch(oldData, newData, v1beta1.Deployment{})

This works fine up till recently, where building the code failed with the following error:

# k8s.io/apimachinery/pkg/util/strategicpatch
../k8s.io/apimachinery/pkg/util/strategicpatch/meta.go:166:17: cannot use kindItem (type *kindItem) as type "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor in argument to s.Schema.Accept:
        *kindItem does not implement "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor (missing VisitArbitrary method)
../k8s.io/apimachinery/pkg/util/strategicpatch/meta.go:181:17: cannot use sliceItem (type *sliceItem) as type "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor in argument to s.Schema.Accept:
        *sliceItem does not implement "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor (missing VisitArbitrary method)
../k8s.io/apimachinery/pkg/util/strategicpatch/types.go:55:5: cannot use kindItem literal (type *kindItem) as type LookupPatchItem in assignment:
        *kindItem does not implement LookupPatchItem (missing VisitArbitrary method)
../k8s.io/apimachinery/pkg/util/strategicpatch/types.go:79:28: cannot use item (type *kindItem) as type "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor in argument to schema.SubSchema().Accept:
        *kindItem does not implement "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor (missing VisitArbitrary method)
../k8s.io/apimachinery/pkg/util/strategicpatch/types.go:118:5: cannot use sliceItem literal (type *sliceItem) as type LookupPatchItem in assignment:
        *sliceItem does not implement LookupPatchItem (missing VisitArbitrary method)
../k8s.io/apimachinery/pkg/util/strategicpatch/types.go:146:28: cannot use item (type *sliceItem) as type "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor in argument to schema.SubSchema().Accept:
        *sliceItem does not implement "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor (missing VisitArbitrary method)
../k8s.io/apimachinery/pkg/util/strategicpatch/types.go:169:18: cannot use item (type *sliceItem) as type "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor in argument to subschema.Accept:
        *sliceItem does not implement "k8s.io/kube-openapi/pkg/util/proto".SchemaVisitor (missing VisitArbitrary method)

**Comment by ericchiang** [comment]
Seeing this too trying to update kube-openapi in kubernetes/kubernetes

cc @mbohlool
