### ISSUE TITLE
Instructions for install and use?

### ISSUE THREAD

**Issue by vsoch** [kubernetes/kube-openapi#375]
Hi! Maybe I'm missing it, but I can't find basic instructions for getting started, install and usage. I'm fumbling around and not really sure what I'm supposed to do, but I was directed to use this tool from the operator-sdk docs. Thanks!

**Comment by T-Lakshmi** [comment]
Hi @vsoch,
Could you please explain in detail exactly which tool you would like to install. and please provide the docs page link you are referring. 

/triage needs-information

**Comment by vsoch** [comment]
Do not close, I think this needs more documentation still.
