### ISSUE TITLE
How to specify a default?

### ISSUE THREAD

**Issue by vsoch** [kubernetes/kube-openapi#376]
hi! I'm generating the Go output for an operator-sdk API (generated with kubebuilder), and everything seems to look okay but my defaults are not passed forward. As an example, here I have a default (defined with a kubebuilder tag) for a timeout in seconds:

```go
// Should the job be limited to a particular number of seconds?
// Approximately one year. This cannot be zero or job won't start
// +kubebuilder:default=31500000
// +optional
DeadlineSeconds int64 `json:"deadlineSeconds"`
```
The default needs to be a large number otherwise the job won't generate! I generate the Go spec as follows:

```bash
./bin/openapi-gen --logtostderr=true -i ./api/${API_VERSION}/ -o "" -O zz_generated.openapi -p ./api/${API_VERSION}/ -h ./hack/boilerplate.go.txt -r "-"
```
But then the deadline seconds default is just the default for the type, which of course is problematic because with a default of 0 a job will never run.

```go
{
	"deadlineSeconds": {
		SchemaProps: spec.SchemaProps{
		Description: "Should the job be limited to a particular number of seconds? Approximately one year. This cannot be zero or job won't start",
		Default:     0,
		Type:        []string{"integer"},
		Format:      "int64",
	},
},
```
Is there another annotation that is needed to specify the default for the generator here? Thanks!

**Comment by Jefftree** [comment]
Not sure how the kubebuilder annotation interacts with this generator, but we specifically look for the `+default` tag for generating the default.

**Comment by vsoch** [comment]
Perfect! The kubebuilder default looks like this:

```
// +kubebuilder:default=31500000
```
I'll try this:

```
// +default=31500000
```
And follow up here to let you know if it works.

**Comment by vsoch** [comment]
That doesn't seem to work - it never lets me build with the error message (e.g., for the field above).

```
DeadlineSeconds: invalid default value (3.15e+07) for non-pointer/non-omitempty. If specified, must be: 0
make: *** [Makefile:105: generate] Error 1
```

**Comment by Jefftree** [comment]
The golang type must be omitempty if you wish to specify a non zero default. Eg: `DeadlineSeconds int64 `json:"deadlineSeconds,omitempty"`

**Comment by vsoch** [comment]
ah gotcha - let me try that! 

I did know that for Go, I'm still relatively new to operators (and for some reason my brain didn't jump to the logical conclusion that these things would be the same). Be back in a few minutes!

**Comment by vsoch** [comment]
That worked like a charm! :partying_face: 

Here is the complete update for a field (as an example) to complete the issue:

```diff
// Should the job be limited to a particular number of seconds?
// Approximately one year. This cannot be zero or job won't start
// +kubebuilder:default=31500000
+ // +default=31500000
// +optional
- DeadlineSeconds int64 `json:"deadlineSeconds"`
+ DeadlineSeconds int64 `json:"deadlineSeconds,omitempty"`
```

Thank you @Jefftree !
