### ISSUE TITLE
Request to remove reference to deprecated module 'github.com/golang/protobuf

### ISSUE THREAD

**Issue by abhithmv** [kubernetes/kube-openapi#397]
Hi,
kube-openapi has a reference to deprecated module 'github.com/golang/protobuf'. Because of which our consuming module depends indirectly on deprecated module.
Is it possible to remove the deprecated module and release a new version of kube-openapi?
Thanks.

**Comment by Jefftree** [comment]
/cc @apelisse @liggitt

Definitely see some use cases of this library in handler.go that could be updated: https://github.com/kubernetes/kube-openapi/blob/master/pkg/handler/handler.go#L111-L117

I haven't looked too deeply, but it looks to also be an indirect dependency based on a library that we use: https://github.com/google/gnostic which also has some usage but also as part of its indirect dependencies from other imports.

**Comment by apelisse** [comment]
I'm not sure what you're suggesting? We definitely use protobuf to serialize the openapi into protobuf.

**Comment by Jefftree** [comment]
github.com/golang/protobuf -> google.golang.org/protobuf

**Comment by apelisse** [comment]
> kube-openapi has a reference to deprecated module 'github.com/golang/protobuf'. Because of which our consuming module depends indirectly on deprecated module.

What problem does this cause?
