### ISSUE TITLE
[Umbrella Issue] Caching library improvements

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kube-openapi#400]
A collection of thoughts from discussion with @apelisse. 

- Should the library be thread safe or should the client handle concurrency?

  + The cache similar to a data structure like a map or list, the client is responsible for locking in those situations. However, data structures like maps and lists function in a way that reading from the data structure makes no mutations and therefore multiple readers could read at once without a lock. The caching data structure will create writes on a read making every operation require a write lock.
  + There is only one entry point for maps and lists. It is easy for clients to create a locked read/write by having all operations funnel through there. The caching library tree is recreated when the cardinality changes and has multiple entry points. Gets can be called on any node in the graph, and not just from a root entry point.
  + By recreating the caching data structure (aka not permitting mergers/transformers to change their input), we don't have a possible conflict of a Get() and new branch addition at the same time. The only concurrency we have to worry about is between multiple Get() functions and single node updates (cached.Replaceable)
- Multi-threaded mergers: https://github.com/kubernetes/kube-openapi/pull/396
  + Related: https://github.com/kubernetes/kube-openapi/pull/399
- Instrumentation: Should we have the option of adding some kind of callback function to record metrics on every function invocation?
- Automatically ignore errors
  We want to avoid checking the error on every step in the cache:

```
cached.NewTransformer(func(result cached.Result[[]byte]) cached.Result[[]byte] {
    if result.Err != nil {
        return cached.NewResultErr[[]byte](result.Err)
    }
    return cached.NewResultOK(result.Data, result.Etag)
}
```

Adding a WrapError function would permit something like:

```
func WrapError(func ([]byte) cached.Result[[]byte]) func(result cached.Result[[]byte]) cached.Result[[]byte]

cached.NewTransformer(WrapError(func(d []byte) cached.Result[[]byte] {
    return cached.NewResultOK([]byte("actual result"), "some-etag")
}))
```
- Determine a way to avoid caching each layer when we have lots of layers of caching (a -> b -> c -> d -> e -> f will cache at every step, defeating the purpose)
- How to avoid caching for "side-effect" types of cache

**Comment by apelisse** [comment]
> How to avoid caching for "side-effect" types of cache

We could make an API that looks like this:
```golang
// Inspect 
func Inspect[T](func(result Result[T]), cached.Data[T]) cached.Data[T]
```

Example:
```golang
cached.Inspect(func(result cached.Result[T]) { 
    fmt.Println("Value in the middle of the chain:", result.Data) 
}, my_cache)
```

That can already be done today, but that will force a copy of the cache to be kept in memory, which is really not good.

**Comment by Jefftree** [comment]
I think it would also be good to define if this is something that can be changed dynamically (eg: same cache could be fetched as a forward vs cache) or a cache state that must be defined when it is created (eg: a cache may either be a forward cache or a caching cache). My gut instinct is that we have a specific purpose for each cache that can be determined on initialization, and having an inspect function to dynamically do this might be a bit overkill.

**Comment by apelisse** [comment]
A lot of the behavior of the cached framework is to retry things when we've seen an error in the previous iteration, but that's not the case with the [`NewStaticCache`](https://github.com/kubernetes/kube-openapi/blob/master/pkg/cached/cache.go#L260-L279), maybe we should make one that doesn't retry?

**Comment by apelisse** [comment]
Also makes me think, should we have a way to maxRetry errors for caches one way or another? Do we want to remerge the spec constantly if one of the source is broken for some reason for example?
