### ISSUE TITLE
Change breaks client-go: gnostic -> gnostic-models

### ISSUE THREAD

**Issue by regnaio** [kubernetes/kube-openapi#404]
Breaking change commit: https://github.com/kubernetes/kube-openapi/commit/38767cdfbb68f871eb458f7cde26177cb65c91e9

Why the change from `gnostic` -> `gnostic-models`?

---

Updated packages using `go get -u ./...`

Then, I tried running a go file using `go run <FILE>`

Got the error message:

```bash
# k8s.io/client-go/applyconfigurations/meta/v1
/go/pkg/mod/k8s.io/client-go@v0.27.2/applyconfigurations/meta/v1/unstructured.go:64:38: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to proto.NewOpenAPIData
```

`proto.NewOpenAPIData` is part of `k8s.io/kube-openapi/pkg/util/proto`

Breaking change occurred somewhere between:
`k8s.io/kube-openapi`: `v0.0.0-20230525220651-2546d827e515` (5/25/2023) ---> `v0.0.0-20230531092745-9b4dcd38a4bf` (5/31/2023)

https://pkg.go.dev/k8s.io/kube-openapi?tab=versions

**Comment by Tochemey** [comment]
Any update on this issue

**Comment by Jefftree** [comment]
Hi, can I ask why you're running `go get -u` on client-go? We pin dependencies for a reason and v0.27.2 is pinned to a version of kube-openapi without the breaking change (https://github.com/kubernetes/client-go/blob/v0.27.2/go.mod)

If you'd like to upgrade client-go, HEAD contains the fixes https://github.com/kubernetes/client-go/commit/2bd3f492360701f79b104bc95dfabf3fb1474c5f for it.

**Comment by imjasonh** [comment]
Moving some conversations from the linked issue:

> Is it expected that the https://github.com/google/gnostic-models repo has one commit, from more than a year ago?
