### ISSUE TITLE
Validator for `byte` does not match mashalling behavior

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes/kube-openapi#424]
kube-openapi code generator encodes all `[]byte` types as a `string` with `byte` format: https://github.com/kubernetes/kube-openapi/blob/34a5c6ab6a70d85502e2e15190fa5cf1b8f29d37/pkg/common/common.go#L218-L240
(Side-note: Most of the formats referred to in this list [arent even supported](https://github.com/kubernetes/kubernetes/blob/a0873d37c58757ac6c2a339af1e4f8d601cdef20/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/formats.go#L26-L51) by our openapi-validator and have no meaning: `int32`, `int64`, `double`, `float`)

The schema validator [uses `IsBase64`](https://github.com/kubernetes/kube-openapi/blob/94abcedd1aa4a1823889c64242463fa23951ce05/pkg/validation/strfmt/default.go#L204) from [github.com/asaskevich/govalidator](https://github.com/asaskevich/govalidator) to determine if a string fits `byte` format. 

This validates the string against the regex:
```regex
^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=|[A-Za-z0-9+\\/]{4})$
```

However, native types deserialize `[]byte` types using the standard go library, which [internally uses `base64.StdEncoding`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/encoding/json/decode.go;l=951-958). `base64.StdEncoding` [follows RFC4648](https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/encoding/base64/base64.go;l=112-114). 

Problem: RFC4648 [allows empty string](https://www.rfc-editor.org/rfc/rfc4648#section-10), but the pattern does not. There may be other differences.

Paths forward: 
1. Change IsBase64 to accept empty string and conform to RFC4648
    1. Pros: 
        - `byte` format has a well-defined meaning 
        - `byte` has same meaning between k8s native and CRD types
    2. Cons: 
        - API Breaking without CRD Validation Ratcheting. Even with ratcheting, regex change would be surprising to users.
            -  Mitigation (suggested by @apelisse): Inject `maxLength: 1` into all usages of `format: byte` by users upon decode.
        - If we wait for CRD Validation Ratcheting we will have a long time before this is fixed 
2. Add new `base64-rfc4648` format. Change code-generator to use new different format for `[]byte`
    1. Pros: 
        - API compatible change
    3. Cons: 
        - New format addition might require we wait for CRD validation ratcheting
            1. Mitigation: Use an inline schema rather than adding a new format, and refer to it using `$ref` until format is added
        - CRDs who want to use RFC4648 are stuck with unspecified `byte` format
            1.  Mitigation: After CRD-Validation Ratcheting is stable, we add new formats for the specific byte RFC. We then migrate native types to use the new format and deprecate old `byte` format.

Impact: Making the schemas accurate for native types is a prerequisite to [KEP-4153: Declarative Validation](https://kep.k8s.io/4153). This is a blocker to using schemas to validate native types.

**Comment by alexzielenski** [comment]
/cc @liggitt 

would appreciate your perspective

**Comment by liggitt** [comment]
I think our treatment of `[]byte` and `format: byte` should match go stdlib handling (e.g. it shouldn't imply `minLength: 1`)

**Comment by apelisse** [comment]
Sounds like you're saying we should break CRD validation, Jordan, how are you doing?

**Comment by liggitt** [comment]
we should obviously only do that once ratcheting would keep from breaking existing data

**Comment by apelisse** [comment]
How would you feel about injecting the minLength in the meantime?

**Comment by alexzielenski** [comment]
I think a less disruptive stopgap measure would be to stop using `byte` format for native types until we have ratcheting in place and can update the format.

**Comment by liggitt** [comment]
what about `oneOf: [{format: byte}, {maxLength:0}]` to allow empty values

**Comment by liggitt** [comment]
> I think a less disruptive stopgap measure would be to stop using `byte` format for native types

For native types, sure.

Would the change we're contemplating also impact schemas generated for custom types in ways that would let non-base64 data in? That doesn't seem great.

**Comment by alexzielenski** [comment]
> Would the change we're contemplating also impact schemas generated for custom types in ways that would let non-base64 data in? That doesn't seem great.

Does `custom types` refer to aggregated apiserver types which generate their spec using k8s openapi codegenerator? Neither our proposed `byte` format changes to match Go handling, nor stopgap schema workarounds with `maxLength` would allow non-base64 data.

`format: byte` -> `anyOf: [{format: byte}, {maxLength:0}]` would strictly allow the additional input `""`

**Comment by liggitt** [comment]
if we stopped using `format: byte` completely, that would allow non-base64 data into custom resources on the server side, which would break if they tried to decode that data into go types using `[]byte`, right?

I didn't know if kube-openapi was used in generating openapi schemas for things like kubebuilder

**Comment by liggitt** [comment]
> How would you feel about injecting the minLength in the meantime?

for fields which don't actually require a minLength > 0, that doesn't seem like a good idea

**Comment by apelisse** [comment]
Offline discussion between Jordan, Alex and I. Conclusions:
- Don't change what we return in openapi from the server. built-in types are accurate, CRDs are (buggily) stricter server-side but it's ok for the server to be more strict than the declarative validation
- Fix the byte bug in our validation fork in kube-openapi to allow "", with a way to opt back into the stricter buggy behavior
- kubectl-validate can update to use the fixed relaxed library
- kube-apiserver can update to use the fixed relaxed library but opt back into stricter buggy validation for CRDs until we land ratcheting
