### ISSUE TITLE
OpenAPI V3 specifications do not mark requestBody as "required"

### ISSUE THREAD

**Issue by tanmaykm** [kubernetes/kube-openapi#427]
This is an example of this issue in the OpenAPI [V3 specification of `createBatchV1NamespacedCronJob`]( https://github.com/kubernetes/kubernetes/blob/0ee315b94cd8d0e27dc1acf0cdb637423de789c2/api/openapi-spec/v3/apis__batch__v1_openapi.json#L6177-L6185)

```
"requestBody": {
  "content": {
    "*/*": {
      "schema": {
        "$ref": "#/components/schemas/io.k8s.api.batch.v1.CronJob"
      }
    }
  }
},
```

The same in the OpenAPI [V2 specification](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json) is marked as required.

```
...
  "post": {
    "consumes": [
      "*/*"
    ],
    "description": "create a CronJob",
    "operationId": "createBatchV1NamespacedCronJob",
    "parameters": [
      {
        "in": "body",
        "name": "body",
        "required": true,
        "schema": {
          "$ref": "#/definitions/io.k8s.api.batch.v1.CronJob"
        }
      },
...
```

From what the specfication [mentions here](https://swagger.io/docs/specification/describing-request-body/), `requestBody` must be marked with `"required": true`, otherwise they are considered optional - "Request bodies are optional by default. To mark the body as required, use required: true."

For the kubernetes requests that accept a request body, the body does seem a mandatory parameter. So looks like the specification generation for OpenAPI v3 needs to address this.

**Comment by apelisse** [comment]
Nice catch, thank you!
